// <auto-generated />
namespace EasyWebsite.DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_type_to_module_content : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_type_to_module_content));
        
        string IMigrationMetadata.Id
        {
            get { return "201512061220113_add_type_to_module_content"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
