// <auto-generated />
namespace EasyWebsite.DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addwebsitefile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addwebsitefile));
        
        string IMigrationMetadata.Id
        {
            get { return "201602140738226_add-website-file"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
